# Generated by Django 4.0.4 on 2022-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brothers', '0004_alter_brother_hometown'),
    ]

    operations = [
        migrations.AddField(
            model_name='brother',
            name='email',
            field=models.EmailField(default='sa@bu.edu', max_length=254),
            preserve_default=False,
        ),
    ]
